### PR TITLE
Code of Conduct

### LINKED ISSUE #1: Code of Conduct and Policy of Inclusiveness
A MD formatted document that borrows much from:

* https://2018.cssconf.com.au/code-of-conduct
* http://geekfeminism.wikia.com/wiki/Conference_anti-harassment/Policy

### PR DESCRIPTION
**Pull request by ericadamski**
closes #1

### CODE REVIEW

**Review by matldupont — APPROVED** [review]
Looks good!

**Review by DanielGarciaGuillen — COMMENTED** [review]
Looks good!

**Review by macdonst — APPROVED** [review]
I'm still trying my best to use "folks" instead of "guys" when speaking but it's not easy to break the habit.

**Comment by ericadamski** [comment]
I agree @macdonst it is super difficult! I fail at it most of the time as well

**Pull request merged**
